services:
  database:
    image: postgres:15-alpine
    container_name: pop_postgres
    environment:
      POSTGRES_USER: melo
      POSTGRES_PASSWORD: root
      POSTGRES_DB: data_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U melo -d data_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  magic:
    image: mageai/mageai:0.9.73   # <--- Mudei para uma versão estável sem logins forçados
    container_name: mage_orchestrator
    command: mage start weather_pipeline
    environment:
      REQUIRE_USER_AUTHENTICATION: 0
    ports:
      - "6789:6789"
    volumes:
      - ./:/home/src/
    restart: always

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=data_test
      - MB_DB_PORT=5432
      - MB_DB_USER=melo
      - MB_DB_PASS=root
      - MB_DB_HOST=database
    depends_on:
      - database
