name: dbt Validation

on:
  push:
    branches:
      - main
      - master

jobs:
  validate-code:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dbt
        run: pip install dbt-postgres

      - name: Criar perfil falso para o teste passar
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          weather_transform:
            target: dev
            outputs:
              dev:
                type: postgres
                host: localhost
                user: robo_github
                password: password_falsa
                port: 5432
                dbname: base_falsa
                schema: analytics
          EOF

      - name: Validar Sintaxe (dbt parse)
        run: |
          cd weather_transform
          dbt parse
